CREATE DATABASE TECH_TEST;

CREATE SCHEMA TECH_TEST.RAW_DATA;

CREATE OR REPLACE TABLE USERS (
    USER_ID INT,
    FIRST_NAME VARCHAR(20),
    JOINED_AT DATE
);

CREATE OR REPLACE TABLE ORDERS (
    ORDER_ID INT,
    USER_ID INT,
    AMOUNT NUMBER(10,2),
    ORDER_DATE DATE
);